# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    
    - name: Run the tests
      run: |
       touch /tmp/issueText.txt
       npm run test 2>/tmp/issueText.txt

    - name: Push to production
      run: |
        git push -f origin develop:production
        
    - name: Setup username to open issue
      if: ${{ failure() }}
      run: |
        echo ::set-env name=username::$(git log -n 1 -s --format='%an')
    - name: Setup issue info to open issue
      if: ${{ failure() }}
      id: issue
      uses: juliangruber/read-file-action@v1
      with:
        path: /tmp/issueText.txt

    - name: Issue making
      if: ${{ failure() }}
      uses: rishabhgupta/git-action-issue@v2
      with:
        token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        title: Tests failed
        body: ${{ steps.issue.outputs.content }}
        assignees: |
          ${{ env.username }}

    - name: Cleanup
      if: ${{ always() }}
      run: rm /tmp/issueText.txt
          

      
    
