# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: |
        npm run test



    - name: Push
      run: |
        git push -f origin develop:production
        
    - name: Check username
      if: ${{ failure() }}
      run: |
        echo ::set-env name=username::$(git log -n 1 -s --format='%an')

    - name: Log errors
      if: ${{ failure() }}
      uses: rishabhgupta/git-action-issue@v2
      with:
        token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        title: Some Issue Title
        body: Some Issue Body
        assignees: |
          ${{ env.username }}
          

      
    
